### ISSUE TITLE
How to inject the code into release builds

### ISSUE THREAD

**Issue by proshoumma** [wix/react-native-repackager#5]
Hi, I'm trying to inject the mock codes into release build. But when I run the following command, it shows `error: unknown option '--customExtensions'`:
```
node node_modules/react-native/local-cli/cli.js run-ios --customExtensions=e2emock
```

I have already executed the command `repackager injectReleaseMockedE2E`.

Any way to inject the code into build release?

**Comment by DanielZlotin** [comment]
you have to first run `repackager setup`, then after than run `repackager injectReleaseMockedE2E ` and it should work

**Comment by DanielZlotin** [comment]
in release builds there's no meaning for the cli args, it's hardcoded by react-native, so repackager injects .e2e support (hardcoded as well)
